language: node_js

node_js:
  - "node"

before_script:
  - npm install

script:
  - npm run deploy-gh

branches:
  only:
    - master

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: .
  on:
    branch: master
